### ISSUE TITLE
Conflicting android.permission.WRITE_EXTERNAL_STORAGE permissions

### ISSUE THREAD

**Issue by bmcharg** [bitstadium/HockeySDK-Cordova#100] opened 2018-01-29 01:15 UTC
I'm having some problems installing the HockeySDK-Cordova plugin in my project on Android. Everything works fine on iOS, but when I install the SDK it appears to cause a permissions conflict with another plugin used in my app.

Without the Hockey plugin installed, my app has the following key in platforms/android/AndroidManifest.xml 

`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`

Everything in my app function as expected, and from the other plugin data can written to external storage.

However, the minute I install the HockeySDK things start to go awry, and the other plugin can no longer write to the external storage. Although my platforms/android/AndroidManifest.xml remains the same once Hockey is installed, I do notice the following in `/platforms/android/build/intermediates/exploded-aar/HockeySDK-Android-5.1.0/AndroidManifest.xml`

`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="18" />`

This same value key can also be found in `/platforms/android/build/intermediates/manifests/full/debug/AndroidManifest.xml`

I believe that this is what is causing the problem, in that for anything >sdk18 the WRITE_EXTERNAL_STORAGE permission is being removed. Indeed, when installing on some devices I can see the requested permissions includes READ_EXTERNAL_STORAGE but not WRITE_EXTERNAL_STORAGE.

To further back this up, if I remove the Hockey plugin, everything works again in our plugin and in the app as a whole.

How is a conflict like this resolved? We need WRITE_EXTERNAL_STORAGE enabled for ALL sdks, not just those <18.

Thanks in advance for any help.

**Comment by bmcharg** [comment] 2018-01-29 01:50
I've found a bit more info in https://support.hockeyapp.net/kb/client-integration-android/hockeyapp-for-android-sdk#permissions-advanced which seems to be for exactly this issue. However, I can't seem to find the correct syntax for my plugin.xml to ensure this is honoured.

`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace"/>`

Should this be in my plugin.xml, or should it actually be in the AAR included in this plugin?

**Comment by TroubleMakerBen** [comment] 2018-01-31 19:03
Hi Brian,

I just responded to the ticket that you opened in our support. We are looking into this and will be in touch. Let's use the support for all discussion.

I'll update this issue as soon as we've found a solution that works for you.

Best,
Benjamin

**Comment by bmcharg** [comment] 2018-01-31 19:11
Great, thanks Ben. Sounds like a plan.

**Comment by rahulbpatel** [comment] 2018-02-06 18:44
What is the ticket?  This just bit me in combination with the cordova-camera-plugin

**Comment by TroubleMakerBen** [comment] 2018-02-06 19:23
Hey @rahulbpatel,

I cannot share support conversations with you as they are private. That said, can you try using the "remove" instead of "replace"?
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="remove" />`
This is not guaranteed to work but might be in your case. We're currently still trying to find a solution for this issue that works reliably.

Best,
Benjamin

**Comment by rahulbpatel** [comment] 2018-02-06 19:35
Hi @TroubleMakerBen,

Where am I adding this?  I'm working on an Ionic / Cordova project and am only working with `config.xml`.  Should I be editing another file?

**Comment by rahulbpatel** [comment] 2018-02-06 20:43
The above doesn't work on a clean platform add.

**Comment by rahulbpatel** [comment] 2018-02-06 21:20
This seemed to work better:

```
<edit-config file="AndroidManifest.xml" mode="merge" target="/manifest">
        <manifest xmlns:tools="http://schemas.android.com/tools" />
    </edit-config>
    <config-file parent="/manifest" target="AndroidManifest.xml">
        <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace" />
    </config-file>
```

**Comment by TroubleMakerBen** [comment] 2018-02-06 21:25
@rahulbpatel does that solve the issue for you?

**Comment by snow-dev** [comment] 2018-02-06 21:28
Problem is on native too, here the above solution work's perfectly, so I'm
gonna try on one of my Ionic project.

**Comment by rahulbpatel** [comment] 2018-02-06 21:33
@TroubleMakerBen yes, now I can build and take pictures.

The cordova build does show a warning message:

> Conflict found, edit-config changes from config.xml will overwrite plugin.xml changes

But I think it's expected since we're trying to do this on purpose.

**Comment by TroubleMakerBen** [comment] 2018-02-07 20:24
Thx for the info @rahulbpatel!

I'm leaving this issue open for better visibility.

**Comment by victorvicky** [comment] 2018-03-27 18:08
After installed this hockey app plugin my native camera plugin not working.
I am using ionic 3 and angular 4 .After uninstall this plugin my native camera is working fine.Kindly give me the solution

**Comment by rahulbpatel** [comment] 2018-03-27 18:58
Re my [comment on Feb 6](https://github.com/bitstadium/HockeySDK-Cordova/issues/100#issuecomment-363568265) I ran into further issues when actually uploading the APK to Google Play:
![hepcure_googleplay](https://user-images.githubusercontent.com/1158576/37986629-d4e9e990-31b0-11e8-92a8-72495c0e3edd.png)

The issue was that in some build sequences the `<config-file>` approach was adding a duplicate `<uses-persmission>` element for `android.permission.WRITE_EXTERNAL_STORAGE`.  Ultimately, what I had to do was use a `before_build` hook to modify the `AndroidManifest.xml` file:

**config.xml**
```
<edit-config file="AndroidManifest.xml" mode="merge" target="/manifest">
  <manifest xmlns:tools="http://schemas.android.com/tools" />
</edit-config>
<hook src="scripts/hooks/fix_hockeyapp_android_write_external_storage_max_sdk_version_issue.js" type="before_build" />
```

**/scripts/hooks/fix_hockeyapp_android_write_external_storage_max_sdk_version_issue.js**
```
'use strict';

const fs = require('fs');
const xml2js = require('xml2js');


module.exports = function (context) {
  const parseString = xml2js.parseString;
  const builder = new xml2js.Builder();
  const manifestPath = context.opts.projectRoot + '/platforms/android/AndroidManifest.xml';
  const androidManifest = fs.readFileSync(manifestPath).toString();

  let manifestRoot;

  if (androidManifest) {

    parseString(androidManifest, (err, manifest) => {
      
      if (err) {
        return console.error(err);
      }

      manifestRoot = manifest['manifest'];

      if (!manifestRoot['uses-permission']) {
        manifestRoot['uses-permission'] = [];
      }

      var permission = manifestRoot['uses-permission'].find(function(item) {
        return item['$']['android:name'] === 'android.permission.WRITE_EXTERNAL_STORAGE';
      });

      if(permission) {

        permission['$']['tools:node'] = 'remove';
        fs.writeFileSync(manifestPath, builder.buildObject(manifest));
      }
    });
  }
};
```

This hook adds a `tools:node="remove"` attribute to the _first_ `<uses-persmission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>` element in `AndroidManifest.xml`.  When the full merged `AndroidManifest.xml` is generated, the permissions added by the HockeyApp `.aar` would be the one that was removed.  This is pretty confusing but hope it helps if my previous solution doesn't work.

**Comment by cchcc** [comment] 2018-06-21 10:09
I had a problem when request permission of WRITE_EXTERNAL_STORAGE because of this.
and solved this by following.  
1. unzip aar
```sh
$ unzip HockeySDK-Android-5.1.0.aar -d HockeySDK-Android-5.1.0
```

2. edit `AndroidManifest.xml` from extracted folder
```xml
<uses-permission
        android:name="android.permission.WRITE_EXTERNAL_STORAGE"
        android:maxSdkVersion="18" />
```
to  
```xml
 <uses-permission
        android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```

3. zip aar
```sh
$  jar cvf HockeySDK-Android-5.1.0.aar -C HockeySDK-Android-5.1.0/ .
```

replace to new aar file.

**Comment by mikeThurmond** [comment] 2018-09-20 23:51
Has anyone else had luck with the hook above?  I am still having issues android.permission.WRITE_EXTERNAL_STORAGE

**Comment by bmourat** [comment] 2018-09-24 05:02
Hi @mikeThurmond,

Could you please provide error context if any? Also, please check if your `AndroidManifest.xml` file is located under `/platforms/android` path.

Best,
Murat

**Closed** 2018-09-25 18:07 UTC
Labels: resolved

**Comment by raujonas** [comment] 2018-11-22 10:15
@snow-dev @mikeThurmond Did you manage to get it work in an Ionic project? I tried the steps mentioned above, but my app still crashes during runtime when I try to open the camera. Without the plugin added it works perfectly.

**Comment by bmourat** [comment] 2018-11-23 08:56
Hi @raujonas 
Could you please describe what steps did you try and how does your resulting manifest looks like?

**Comment by mikeThurmond** [comment] 2018-11-23 17:11
@raujonas I did get it to work, I did the following:
 
I took the hook from above and made a couple changes.  I also had to import the libraries fs and xml2js
via node or homebrew (it was one of the two, I just can't remember)

1) I had to edit the path of this line from 
const manifestPath = context.opts.projectRoot + '/platforms/android/AndroidManifest.xml';
to
'/platforms/android/app/src/main/AndroidManifest.xml' 

you might have to edit the path to something else, just check and make sure it lines up to your android manifest file during the build/prepare steps

2) I changed this line near the bottom from 

permission['$']['tools:node'] = 'remove';  
to 
permission['$']['tools:node'] = 'replace';

I added this line to the config.xml and changed the type to after_prepare
 <hook src="/hooks/override_writes.js" type="after_prepare" />

I had to reference the Cordova docs on hooks to help with this step.

Hope this helps

**Comment by raujonas** [comment] 2018-11-25 09:44
@bmourat @mikeThurmond thank you for your help! These are the steps I tried:

1. I installed the plugin like it is mentioned here: https://www.npmjs.com/package/ionic-hockeyapp. After this step I get the error 20 as expected when I will use the camera.

2. Then I added the javascript file from above. My AndroidManifest.xml is in the same path as yours, so I changed the path also to 
`const manifestPath = context.opts.projectRoot + '/platforms/android/app/src/main/AndroidManifest.xml';`

3. I also changed the permission at the end of the file:
`        permission['$']['tools:node'] = 'replace';`

4. Then I added the hook to my config.xml, where I changed the type also to after_prepare:
`<edit-config file="AndroidManifest.xml" mode="merge" target="/manifest">
        <manifest xmlns:tools="http://schemas.android.com/tools" />
    </edit-config>
    <hook src="scripts/hooks/fix_hockeyapp_android_write_external_storage_max_sdk_version_issue.js" type="after_prepare" />`

After I did these steps, I do not get the error 20 as before when I open the camera. The camera opens, but then my app crashes without any further information. So I had the idea to consider logcat:

` 11-25 10:30:47.110 17919 17919 D CordovaActivity: Paused the activity.                                                                                                                                                                                                           
11-25 10:30:47.127 17919 18012 W PluginManager: THREAD WARNING: exec() call to Camera.takePicture blocked the main thread for 131ms. Plugin should use CordovaInterface.getThreadPool().                                                                                         
11-25 10:30:47.127  1653  1667 E memtrack: Couldn't load memtrack module                                                                                                                                                                                                         
11-25 10:30:47.127  1653  1667 W android.os.Debug: failed to get memory consumption info: -1                                                                                                                                                                                     
11-25 10:30:47.131 17919 17919 D CordovaWebViewImpl: >>> loadUrl(javascript:cordova.plugins.backgroundMode._setActive(true);cordova.plugins.backgroundMode.onactivate(null);cordova.plugins.backgroundMode.fireEvent('activate',null);)                                          
11-25 10:30:47.182  1653  1667 E memtrack: Couldn't load memtrack module                                                                                                                                                                                                         
11-25 10:30:47.183  1653  1667 W android.os.Debug: failed to get memory consumption info: -1                                                                                                                                                                                     
11-25 10:30:47.187  3029  3029 V CAM_QuickActivity: START onCreate: Activity = com.android.camera.CaptureActivity@8c4e868                                                                                                                                                        
11-25 10:30:47.187  3029  3029 V CAM_Profiler: [  0.000ms][ui] GUARD: CameraActivity.onCreateTasks - START                                                                                                                                                                       
11-25 10:30:47.188  3029  3029 D CAM_LocationManager: Using legacy location provider.                                                                                                                                                                                            
11-25 10:30:47.202  3029  3029 W SoundPool: Use of stream types is deprecated for operations other than volume control                                                                                                                                                           
11-25 10:30:47.202  3029  3029 W SoundPool: See the documentation of SoundPool() for what to use instead with android.media.AudioAttributes to qualify your playback use case                                                                                                    
11-25 10:30:47.202  3029  3029 I CAM_OneCamFtrCnfgCrtr: CaptureModule? true                                                                                                                                                                                                      
11-25 10:30:47.203  3029  3029 V CAM_Profiler: [ 15.525ms][ui] GUARD: CameraActivity.onCreateTasks - [ 0.100ms] Glide.setup                                                                                                                                                      
11-25 10:30:47.213  1653  1667 E memtrack: Couldn't load memtrack module                                                                                                                                                                                                         
11-25 10:30:47.215  1653  1667 W android.os.Debug: failed to get memory consumption info: -1                                                                                                                                                                                     
11-25 10:30:47.216  3029  3029 V CAM_Profiler: [ 26.122ms][ui] GUARD: CameraActivity.onCreateTasks - [10.597ms] OneCameraManager.get                                                                                                                                             
11-25 10:30:47.228  3029 18136 V NuMediaExtractor: setDataSource fd=147 (/system/media/audio/ui/camera_click.ogg), offset=0, length=5951                                                                                                                                         
11-25 10:30:47.242 17919 17919 W zygote64: Attempt to remove non-JNI local reference, dumping thread                                                                                                                                                                             
11-25 10:30:47.264  1653  1667 E memtrack: Couldn't load memtrack module                                                                                                                                                                                                         
11-25 10:30:47.264  1653  1667 W android.os.Debug: failed to get memory consumption info: -1                                                                                                                                                                                     
11-25 10:30:47.264 17919 17919 D AndroidRuntime: Shutting down VM                                                                                                                                                                                                                
11-25 10:30:47.266 17919 17919 E AndroidRuntime: FATAL EXCEPTION: main                                                                                                                                                                                                           
**11-25 10:30:47.266 17919 17919 E AndroidRuntime: java.lang.RuntimeException: Unable to create service de.appplant.cordova.plugin.background.ForegroundService: java.lang.SecurityException: Neither user 10062 nor current process has android.permission.WAKE_LOCK.**             
11-25 10:30:47.266 17919 17919 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3349)                                                                                                                                              
11-25 10:30:47.266 17919 17919 E AndroidRuntime:        at android.app.ActivityThread.-wrap4(Unknown Source:0)                                                                                                                                                                   
11-25 10:30:47.266 17919 17919 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)                                                                                                                                                  
11-25 10:30:47.266 17919 17919 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)                                                                                                                                                                  
11-25 10:30:47.266 17919 17919 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)                                                                                                                                                                               
11-25 10:30:47.266 17919 17919 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6494)                                                                                                                                                             
11-25 10:30:47.266 17919 17919 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)                                                                                                                                                                        
11-25 10:30:47.266 17919 17919 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)                                                                                                                                     
11-25 10:30:47.266 17919 17919 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)                                                                                                                                                          
11-25 10:30:47.266 17919 17919 E AndroidRuntime: Caused by: java.lang.SecurityException: Neither user 10062 nor current process has android.permission.WAKE_LOCK.                                                                                                                
11-25 10:30:47.266 17919 17919 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2004)                                                                                                                                                                     
11-25 10:30:47.266 17919 17919 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1950)                                                                                                                                                                     
11-25 10:30:47.266 17919 17919 E AndroidRuntime:        at android.os.IPowerManager$Stub$Proxy.acquireWakeLock(IPowerManager.java:405)                                                                                                                                           
11-25 10:30:47.266 17919 17919 E AndroidRuntime:        at android.os.PowerManager$WakeLock.acquireLocked(PowerManager.java:1352)                                                                                                                                                
11-25 10:30:47.266 17919 17919 E AndroidRuntime:        at android.os.PowerManager$WakeLock.acquire(PowerManager.java:1318)                                                                                                                                                      
11-25 10:30:47.266 17919 17919 E AndroidRuntime:        at de.appplant.cordova.plugin.background.ForegroundService.keepAwake(ForegroundService.java:124)                                                                                                                         
11-25 10:30:47.266 17919 17919 E AndroidRuntime:        at de.appplant.cordova.plugin.background.ForegroundService.onCreate(ForegroundService.java:94)                                                                                                                           
11-25 10:30:47.266 17919 17919 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3339)                                                                                                                                              
11-25 10:30:47.266 17919 17919 E AndroidRuntime:        ... 8 more                            `               

What makes me wonder is the following log entry:
**11-25 10:30:47.266 17919 17919 E AndroidRuntime: java.lang.RuntimeException: Unable to create service de.appplant.cordova.plugin.background.ForegroundService: java.lang.SecurityException: Neither user 10062 nor current process has android.permission.WAKE_LOCK.**                                                                                                                                                                                  

So I suggest that there is now a problem with another plugin?

**Comment by raujonas** [comment] 2018-11-26 10:09
Hey guys, thank you again for your help! I think sometimes it just helps to write all steps down and to think about them again, so it seems that it is working now.

What I did in fact is deleting the platforms and plugins folder and then started a new build. I could image that the permissions I mentioned above are missed after the build, because I tried with the "remove" value instead the "replace" on my first try. Now the script handles all permissions correctly and I can use the camera without a crash (because the were in the manifest from the beginning).

Thank you again! Maybe this helps also someone else.

**Comment by arajanrai** [comment] 2019-01-25 22:22
> <edit-config file="AndroidManifest.xml" mode="merge" target="/manifest"> <manifest xmlns:tools="http://schemas.android.com/tools" /> </edit-config> <config-file parent="/manifest" target="AndroidManifest.xml"> <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace" /> </config-file>

Also please remove platform and add it again

**Comment by arajanrai** [comment] 2019-01-25 22:23
<edit-config file="AndroidManifest.xml" mode="merge" target="/manifest">
  <manifest xmlns:tools="http://schemas.android.com/tools" />
</edit-config>
<config-file parent="/manifest" target="AndroidManifest.xml">
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace" />
</config-file>
remove platform folder also

**Comment by parthnayak7448** [comment] 2019-02-20 19:32
@bmourat , @raujonas , @mikeThurmond , @arajanrai    Can anyone please mention all the steps properly from path of all the files where we have to replace XXX lines. While just mentioning change this line to this is not happening for us. It will be great if anyone write files path and changes for that file.

**Comment by annakocheshkova** [comment] 2019-02-21 08:15
Hi @parthnayak7448 !
Sure, here are the detailed steps:
So lets say you have an app named **TestApp**.

1. Remove `TestApp/platforms` folder;
2. Open your `config.xml` and add the following lines:
```
<edit-config file="AndroidManifest.xml" mode="merge" target="/manifest">
  <manifest xmlns:tools="http://schemas.android.com/tools" />
</edit-config>
<hook src="scripts/hooks/fix_hockeyapp_android_write_external_storage_max_sdk_version_issue.js" type="after_prepare" />
```
3. In the root of your project, create a folder named `scripts`, and under it a folder named `hooks`;
4. Put the following file with the name `fix_hockeyapp_android_write_external_storage_max_sdk_version_issue.js` into `hooks`:
```js
'use strict';

const fs = require('fs');
const xml2js = require('xml2js');

module.exports = function (context) {
  const parseString = xml2js.parseString;
  const builder = new xml2js.Builder(); 
  const manifestPath = context.opts.projectRoot + '/platforms/android/AndroidManifest.xml';
  const androidManifest = fs.readFileSync(manifestPath).toString();
  let manifestRoot;

  if (androidManifest) {
    parseString(androidManifest, (err, manifest) => {      
      if (err) {
        return console.error(err);
      }
      manifestRoot = manifest['manifest'];

      if (!manifestRoot['uses-permission']) {
        manifestRoot['uses-permission'] = [];
      }

      var permission = manifestRoot['uses-permission'].find(function(item) {
        return item['$']['android:name'] === 'android.permission.WRITE_EXTERNAL_STORAGE';
      });

      if(permission) {
        permission['$']['tools:node'] = 'replace';
        fs.writeFileSync(manifestPath, builder.buildObject(manifest));
      }
    });
  }
};
```
Make sure that the path `const manifestPath = context.opts.projectRoot + '/platforms/android/AndroidManifest.xml';` is correct and leads to your `AndroidManifest.xml`;
5. `npm i xml2js`;
6. `corodva platform add android`;
7. Start the app.

I also noticed that this fix does not work with `cordova >= 7.0.0`. So if you have higher cordova versions:
1. You should skip step 2 from the instructions above;
2. Change the following line in the `fix_hockeyapp_android_write_external_storage_max_sdk_version_issue` script:
`const manifestPath = context.opts.projectRoot + '/platforms/android/AndroidManifest.xml';`
to this line:
`const manifestPath = context.opts.projectRoot + '/platforms/android/app/src/main/AndroidManifest.xml';`
3. In the `fix_hockeyapp_android_write_external_storage_max_sdk_version_issue` script, add the following line:
`manifestRoot['$']['xmlns:tools'] = 'http://schemas.android.com/tools';`
after this line:
`manifestRoot = manifest['manifest'];`.

**Comment by parthnayak7448** [comment] 2019-02-21 20:34
Hey @annakocheshkova ,

Thanks for brief description. 
But still this solution didn't work for me and giving same error '20' 

Android: 8.0.0 
Ionic 3

**Comment by annakocheshkova** [comment] 2019-02-22 17:56
Hi @parthnayak7448, sorry for the issues you are experiencing.
What is your `cordova-android` version? Can you share your `config.xml` contents with me?
Thanks!

**Comment by parthnayak7448** [comment] 2019-02-27 02:52
Hey @annakocheshkova 

My Android version is 8.0.0.

`<?xml version='1.0' encoding='utf-8'?>
<widget id="com.test.test" version="1.2.5" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>test</name>
    <description>test</description>
   <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <preference name="ScrollEnabled" value="false" />
    <preference name="android-minSdkVersion" value="19" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="FadeSplashScreenDuration" value="300" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="3000" />
    <platform name="android">
        <allow-intent href="market:*" />
        <resource-file src="resources/android/notification_icon/drawable-mdpi/ic_stat_noti_iconpng.png" target="app/src/main/res/drawable-mdpi/ic_stat_noti_iconpng.png" />
        <resource-file src="resources/android/notification_icon/drawable-hdpi/ic_stat_noti_iconpng.png" target="app/src/main/res/drawable-hdpi/ic_stat_noti_iconpng.png" />
        <resource-file src="resources/android/notification_icon/drawable-xhdpi/ic_stat_noti_iconpng.png" target="app/src/main/res/drawable-xhdpi/ic_stat_noti_iconpng.png" />
        <resource-file src="resources/android/notification_icon/drawable-xxhdpi/ic_stat_noti_iconpng.png" target="app/src/main/res/drawable-xxhdpi/ic_stat_noti_iconpng.png" />
        <resource-file src="resources/android/notification_icon/drawable-xxxhdpi/ic_stat_noti_iconpng.png" target="app/src/main/res/drawable-xxxhdpi/ic_stat_noti_iconpng.png" />
        <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
        <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
        <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
        <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
        <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
        <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png" />
        <splash density="land-mdpi" src="resources/android/splash/drawable-land-mdpi-screen.png" />
        <splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png" />
        <splash density="land-xhdpi" src="resources/android/splash/drawable-land-xhdpi-screen.png" />
        <splash density="land-xxhdpi" src="resources/android/splash/drawable-land-xxhdpi-screen.png" />
        <splash density="land-xxxhdpi" src="resources/android/splash/drawable-land-xxxhdpi-screen.png" />
        <splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png" />
        <splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png" />
        <splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png" />
        <splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png" />
        <splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png" />
        <splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png" />
        <preference name="APP_SECRET" value="" />
        <preference name="APPCENTER_CRASHES_ALWAYS_SEND" value="true" />
        <resource-file src="google-services.json" target="app/google-services.json" />
    </platform>
    <platform name="ios">
        <preference name="APP_SECRET" value="" />
        <preference name="APPCENTER_CRASHES_ALWAYS_SEND" value="true" />
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <icon height="57" src="resources/ios/icon/icon.png" width="57" />
        <icon height="114" src="resources/ios/icon/icon@2x.png" width="114" />
        <icon height="40" src="resources/ios/icon/icon-40.png" width="40" />
        <icon height="80" src="resources/ios/icon/icon-40@2x.png" width="80" />
        <icon height="120" src="resources/ios/icon/icon-40@3x.png" width="120" />
        <icon height="50" src="resources/ios/icon/icon-50.png" width="50" />
        <icon height="100" src="resources/ios/icon/icon-50@2x.png" width="100" />
        <icon height="60" src="resources/ios/icon/icon-60.png" width="60" />
        <icon height="120" src="resources/ios/icon/icon-60@2x.png" width="120" />
        <icon height="180" src="resources/ios/icon/icon-60@3x.png" width="180" />
        <icon height="72" src="resources/ios/icon/icon-72.png" width="72" />
        <icon height="144" src="resources/ios/icon/icon-72@2x.png" width="144" />
        <icon height="76" src="resources/ios/icon/icon-76.png" width="76" />
        <icon height="152" src="resources/ios/icon/icon-76@2x.png" width="152" />
        <icon height="167" src="resources/ios/icon/icon-83.5@2x.png" width="167" />
        <icon height="29" src="resources/ios/icon/icon-small.png" width="29" />
        <icon height="58" src="resources/ios/icon/icon-small@2x.png" width="58" />
        <icon height="87" src="resources/ios/icon/icon-small@3x.png" width="87" />
        <icon height="1024" src="resources/ios/icon/icon-1024.png" width="1024" />
        <splash height="1136" src="resources/ios/splash/Default-568h@2x~iphone.png" width="640" />
        <splash height="1334" src="resources/ios/splash/Default-667h.png" width="750" />
        <splash height="2208" src="resources/ios/splash/Default-736h.png" width="1242" />
        <splash height="1242" src="resources/ios/splash/Default-Landscape-736h.png" width="2208" />
        <splash height="1536" src="resources/ios/splash/Default-Landscape@2x~ipad.png" width="2048" />
        <splash height="2048" src="resources/ios/splash/Default-Landscape@~ipadpro.png" width="2732" />
        <splash height="768" src="resources/ios/splash/Default-Landscape~ipad.png" width="1024" />
        <splash height="2048" src="resources/ios/splash/Default-Portrait@2x~ipad.png" width="1536" />
        <splash height="2732" src="resources/ios/splash/Default-Portrait@~ipadpro.png" width="2048" />
        <splash height="1024" src="resources/ios/splash/Default-Portrait~ipad.png" width="768" />
        <splash height="960" src="resources/ios/splash/Default@2x~iphone.png" width="640" />
        <splash height="480" src="resources/ios/splash/Default~iphone.png" width="320" />
        <splash height="2732" src="resources/ios/splash/Default@2x~universal~anyany.png" width="2732" />
    </platform>
    <edit-config file="*-Info.plist" mode="merge" target="NSLocationWhenInUseUsageDescription">
        <string>need location access to find things nearby</string>
    </edit-config>
    <allow-navigation href="http://169.254.194.196:8102" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <plugin name="ionic-plugin-keyboard" spec="^2.2.1" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.3" />
    <plugin name="cordova-plugin-device" spec="^1.1.7" />
    <plugin name="cordova-plugin-splashscreen" spec="^4.1.0" />
    <plugin name="cordova-plugin-network-information" spec="^1.3.4" />
    <plugin name="cordova-sqlite-storage" spec="^2.3.3" />
    <plugin name="phonegap-plugin-barcodescanner" spec="^7.1.2">
        <variable name="ANDROID_SUPPORT_V4_VERSION" value="27.+" />
        <variable name="CAMERA_USAGE_DESCRIPTION" value=" " />
    </plugin>
    <plugin name="cordova-plugin-statusbar" spec="^2.4.2" />
    <plugin name="cordova-plugin-geolocation" spec="^4.0.1">
        <variable name="GEOLOCATION_USAGE_DESCRIPTION" value="To locate you" />
    </plugin>
    <plugin name="cordova.plugins.diagnostic" spec="^4.0.8" />
    <plugin name="cordova-plugin-file-transfer" spec="^1.7.1" />
    <plugin name="cordova-plugin-file" spec="^6.0.1" />
    <plugin name="cordova-plugin-android-permissions" spec="^1.0.0" />
    <plugin name="cordova-plugin-camera" spec="^4.0.3" />
    <plugin name="cordova-plugin-globalization" spec="^1.11.0" />
    <plugin name="cordova-plugin-ms-azure-mobile-apps" spec="^2.0.2" />
    <plugin name="cordova-plugin-request-location-accuracy" spec="^2.2.3" />
    <plugin name="cordova-plugin-app-version" spec="^0.1.9" />
    <plugin name="cordova-android-support-gradle-release" spec="^1.4.4">
        <variable name="ANDROID_SUPPORT_VERSION" value="27.+" />
    </plugin>
    <plugin name="cordova-plugin-image-picker" spec="1.1.3">
        <variable name="PHOTO_LIBRARY_USAGE_DESCRIPTION" value=" " />
    </plugin>
    <plugin name="cordova-plugin-appcenter-crashes" spec="0.3.2" />
    <plugin name="phonegap-plugin-push" spec="2.2.3">
        <variable name="ANDROID_SUPPORT_V13_VERSION" value="27.+" />
        <variable name="FCM_VERSION" value="11.6.2" />
        <variable name="SENDER_ID" value="317261703215" />
    </plugin>
    <plugin name="cordova-play-services-version-adapter" spec="1.0.2" />
    <engine name="browser" spec="~5.0.3" />
    <engine name="ios" spec="~4.5.5" />
    <engine name="android" spec="8.0.0" />
</widget>
`

**Comment by annakocheshkova** [comment] 2019-02-28 08:34
Hi @parthnayak7448!
I don't see `
<hook src="scripts/hooks/fix_hockeyapp_android_write_external_storage_max_sdk_version_issue.js" type="after_prepare" />` line in the config. My bad, seems like it is necessary on all android versions.
I've edited my comment to reflect that.

**Comment by annakocheshkova** [comment] 2019-03-11 08:20
@parthnayak7448 just a friendly ping :) Did you manage to get it working?

**Comment by ParthNayak5487** [comment] 2019-03-15 22:18
> Hi @parthnayak7448!
> I don't see ` <hook src="scripts/hooks/fix_hockeyapp_android_write_external_storage_max_sdk_version_issue.js" type="after_prepare" />` line in the config. My bad, seems like it is necessary on all android versions.
> I've edited my comment to reflect that.

Sorry before sending you config i have remove hook tag because as i told it was not working so undo all the steps that i followed. 

> @parthnayak7448 just a friendly ping :) Did you manage to get it working?

Anna i haven't try after that. my main concern to use hockey app was to get error reports which i replace with app centre plugin. But for sure i will try again very soon and will update you later on.
