### ISSUE TITLE
Cordova Camera and Hockey App permission issue

### ISSUE THREAD

**Issue by mikeThurmond** [bitstadium/HockeySDK-Cordova#106] opened 2018-09-17 18:45 UTC
I have referenced the docs from

 [here](https://support.hockeyapp.net/kb/client-integration-android/hockeyapp-for-android-sdk#permissions-advanced) and the closed issue [here](https://github.com/bitstadium/HockeySDK-Cordova/issues/101)

According to the link above, I cannot add the correct code to the [config.xml](https://github.com/bitstadium/HockeySDK-Cordova/issues/101#issuecomment-412766595)

Do you have a suggestion or a fix besides writing a hook?

**Comment by mikeThurmond** [comment] 2018-09-17 21:58
I used the hook at the bottom of https://github.com/bitstadium/HockeySDK-Cordova/issues/100 for a fix.

**Comment by MatkovIvan** [comment] 2018-09-20 08:03
Hi @mikeThurmond,

It looks like you've already solved the issue based on responses in the linked issues. So, this one can be closed because it's duplicate of the linked ones and actually has already been solved.

Please let me know if there is something I missed or you still face it.

Thanks,
Ivan

**Comment by mikeThurmond** [comment] 2018-09-20 18:58
@MatkovIvan,

Actually, the problem is occurring again.  I thought I had fixed it but apparently, the camera stopped working again.

**Comment by mikeThurmond** [comment] 2018-09-20 23:04
I am also currently working on requesting permissions at runtime, as stated in the Cordova docs but am running into this issue https://github.com/NeoLSN/cordova-plugin-android-permissions/issues/52. Do I need to open a service ticket with you guys?

**Closed** 2018-09-25 18:07 UTC
