### ISSUE TITLE
Checking for updates is not work

### ISSUE THREAD

**Issue by sutinee742** [bitstadium/HockeySDK-Cordova#78] opened 2017-06-12 10:32 UTC
hi!
i have a problem on checking for updates is not work.
i created a new version from this link -> https://support.hockeyapp.net/kb/app-management-2/how-to-create-a-new-version

i add plugins along with the following associated platform, increased the CFBundle Version (iOS) with each new build in config.xml and edit code in index.js to start hockeyappSDK.

this source -> https://github.com/sutinee742/HelloAngstrom

Then i built ipa file with phonegap tool.

when uploaded .ipa on hockeyapp and updated another version, tested it. i found feedback function and forcecrash fucntion work, but check for updates is not display updated ui.
https://files.slack.com/files-tmb/T0K40UXFX-F5S71DRN0-bd9a4bad9f/img_0024_1024.jpg

**Comment by bmourat** [comment] 2017-06-15 11:51
Hi @sutinee742 !
I checked your app and for me update function is working properly. My idea is that something wrong is going with your versions. Could you please provide information on:
- Version and BuildNumber for your new version that is on HockeyApp portal
- ios-CFBundleVersion and version from config.xml for your old app that is not updating

Thanks,
Murat

**Comment by sutineeangs** [comment] 2017-06-21 08:47
Version and BuildNumber on HockeyApp and ios-CFBundleVersion and version from config.xml -> http://imgur.com/a/P79sM

**Comment by sutineeangs** [comment] 2017-06-21 08:52
@bmourat this is my versions on HockeyApp  and config.xml -> http://imgur.com/a/P79sM

**Comment by bmourat** [comment] 2017-06-22 08:16
Hey @sutinee742 I still can not reproduce this issue, even with the versions you provided update part is working. But i'll keep on investigating this!

**Comment by bmourat** [comment] 2017-06-29 21:50
Hi @sutinee742 
To be clear, you are using version 2.2.4 of HockeySDK-Cordova plugin and this source https://github.com/sutinee742/HelloAngstrom and update function doesn't work when using version from this image http://imgur.com/a/P79sM. Is that right?

**Comment by TroubleMakerBen** [comment] 2017-09-27 21:54
Hey folks,

Is this issue still a problem? If so, let me know until the end of the week, I'll close the issue if I don't hear from anyone by then.

Cheers!
Benny

**Comment by blumk** [comment] 2017-12-13 19:55
Hi @TroubleMakerBen
I'm facing the same issue in my Ionic App on Android. I've increased the config.xml and uploaded the build to HockeyApp. The Android build is signed (with the keystore file).
When deploying the app to my device through USB the update dialog appears and it pulls the newest build from HockeyApp.

**Comment by blumk** [comment] 2017-12-13 21:13
@TroubleMakerBen Just saw your latest release. This issue no longer occurs on Android with release 5.1.0. Will test it on iOS next.

**Comment by TroubleMakerBen** [comment] 2017-12-14 07:50
Hey @blumk,

thx for the confirmation! Please let me know if you're running into any issues.

Benjamin

PS: please check out version 5.1.1 for iOS =)

**Comment by junalmeida** [comment] 2017-12-20 10:22
I cannot use this too. trackEvent method works, I can see events at hockeyapp dashboard, but checkForUpdate returns success but no dialog is shown when there is a new version. 

![image](https://user-images.githubusercontent.com/991675/34202383-c09bb872-e55e-11e7-84cc-678df99a46b9.png)

![image](https://user-images.githubusercontent.com/991675/34202418-d9266108-e55e-11e7-9d58-e5d04573513d.png)

**Comment by blumk** [comment] 2017-12-20 14:10
@TroubleMakerBen @junalmeida 
I can confirm the issue on iOS, I'm using 5.1.1 and the update dialog does not show on iOS. Same code on Android works as expected.

**Comment by TroubleMakerBen** [comment] 2017-12-20 16:21
Thx for letting us know. We're looking into this.

**Comment by bmourat** [comment] 2017-12-22 07:57
@junalmeida @blumk 
I can't reproduce this behavior, could you please provide following info:
1. version of Cordova and ios-platform
2. version of plugin
3. testing device type and version
4. versions of the app on the device and on the portal 

Also, it would be great if you can share some sample project to repro this :)

**Comment by blumk** [comment] 2018-01-04 10:36
@bmourat 
I'm using Ionic 3.9.2 with the Ionic wrapper for HockeyApp :
https://github.com/hicsail/ionic-hockeyapp

`"cordova-ios": "4.5.4"`
`"cordova-plugin-hockeyapp": "^5.1.1"`
`"ionic-hockeyapp": "^0.2.0"`

Testing devices:
- iPhone 5 with iOS 10.3.3
- iPhone X with iOS 11.2.1

I'm using an Ionic Pro account to build the app. Manually uploading the *.ipa package to hockey app.
App build/version number always match and are incrementally increased for every release. Device info on the hockey app portal matches the actual device info.

Building an Android app with the same code base on Ionic Pro triggers the Hockey App update dialog on Android.

**Comment by blumk** [comment] 2018-01-12 08:50
@bmourat @TroubleMakerBen Started receiving update dialogs this week on my iOS devices.

I have not made any changes to some apps (code, hockeyapp.net). One app was used to reproduce the app on Dec 13th (see above).

It looks like this was an issue with the HockeyApp backend not sending out the update signal, the SDK seems to be fine (5.1.1).

**Comment by jamesdixon** [comment] 2018-02-22 17:34
This is happening to me using Android. Using 5.1.2

**Comment by TroubleMakerBen** [comment] 2018-02-22 18:10
Hi folks,

We're not aware of any issues in our SDKs and the backend. It's very unlikely that App Center had anything to do with it as App Center does not interfere with HockeyApp.

@jamesdixon 
Can you launch the app and share the output of LogCat with me, please?

**Comment by TroubleMakerBen** [comment] 2018-02-22 23:09
I just tried to repro this once more with an empty cordova hello world and I get the prompt for new updates right away (ok, I waited like 5min until I launched the app again but that shouldn't really matter).

Best,
Benjamin

**Comment by junalmeida** [comment] 2018-04-15 20:41
@blumk @bmourat I still cannot see the update alert on iOS, neither the devices or simulator. 
Debugging through xcode I can confirm that appidentifier is correct under sharedHockeyManager. 
I opened an issue under HockeySDK-iOS: https://github.com/bitstadium/HockeySDK-iOS/issues/515

**Comment by junalmeida** [comment] 2018-04-18 20:08
Now it works for me. Turns out that my iOS app versions are restricted to specific distribution groups, and this does not work on iOS, although the same scenario works as expected on Android version. 

Once I removed the restriction, updates starts to pop out.

**Comment by TroubleMakerBen** [comment] 2018-04-19 18:12
Hi @junalmeida,

let's continue the discussion that you started in  [bitstadium/HockeySDK-iOS#515](https://github.com/bitstadium/HockeySDK-iOS/issues/515).
Unfortunately, in-app updates for restricted releases are currently not supported in Cordova iOS as stated in the [readme.md](https://github.com/bitstadium/HockeySDK-Cordova#api-reference).

Sorry for any confusion this has caused.

**Closed by TroubleMakerBen** 2018-04-19 18:12 UTC
