### ISSUE TITLE
A plugin in your app does not support the compulsory arm64 (64-bit support) architecture.

### ISSUE THREAD

**Issue by AndrewCer** [bitstadium/HockeySDK-Cordova#38] opened 2016-04-06 16:58 UTC
Our iOS build fails with above error message whenever I try to integrate this into the app. I'm using PhoneGap Build. 
In my config.xml:
  `<plugin name="https://github.com/bitstadium/HockeySDK-Cordova.git"/>`

PhoneGap seems to be fetching and installing the plugin alright. 
From build logs:
`Fetching plugin "https://github.com/bitstadium/HockeySDK-Cordova.git" via git clone
Repository "https://github.com/bitstadium/HockeySDK-Cordova.git" checked out to git ref "master" at "1d1d952".
Installing "cordova-plugin-hockeyapp" at "2.2.1" for ios`

However the build fails at the very end on the command:
`Ld build/appName.build/Release-iphoneos/appName.build/Objects-normal/arm64/appName normal arm64` (replaced our real app name for appName)

I'm pretty sure the failure is related to this plugin because when I remove HockeySDK from config.xml, the .ipa is built correctly.

**Comment by lostintangent** [comment] 2016-04-07 01:48
@AndrewCer Apologies about this! I will investigate what the cause of this might be. We hadn't seen this issue before.

**Comment by johnyso** [comment] 2016-04-07 13:50
Same issue here, 
running version 2.1.0 everything works fine. 

I tried to build my project with the 2.2.1 version.
after running a `ionic build ios` i get the same issue.
here is the problem with the undefined symbols:
```
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_PHAsset", referenced from:
      objc-class-ref in HockeySDK(BITFeedbackManager.o)
  "_OBJC_CLASS_$_PHFetchOptions", referenced from:
      objc-class-ref in HockeySDK(BITFeedbackManager.o)
  "_OBJC_CLASS_$_PHImageManager", referenced from:
      objc-class-ref in HockeySDK(BITFeedbackManager.o)
  "_OBJC_CLASS_$_PHImageRequestOptions", referenced from:
      objc-class-ref in HockeySDK(BITFeedbackManager.o)
  "_OBJC_CLASS_$_PHPhotoLibrary", referenced from:
      objc-class-ref in HockeySDK(BITFeedbackManager.o)
  "_deflate", referenced from:
      -[NSData(GZIP) gzippedDataWithCompressionLevel:] in HockeySDK(BITCategoryContainer.o)
  "_deflateEnd", referenced from:
      -[NSData(GZIP) gzippedDataWithCompressionLevel:] in HockeySDK(BITCategoryContainer.o)
  "_deflateInit2_", referenced from:
      -[NSData(GZIP) gzippedDataWithCompressionLevel:] in HockeySDK(BITCategoryContainer.o)
  "_inflate", referenced from:
      -[NSData(GZIP) gunzippedData] in HockeySDK(BITCategoryContainer.o)
  "_inflateEnd", referenced from:
      -[NSData(GZIP) gunzippedData] in HockeySDK(BITCategoryContainer.o)
  "_inflateInit2_", referenced from:
      -[NSData(GZIP) gunzippedData] in HockeySDK(BITCategoryContainer.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
on the very end there is the same output AndrewCer reported already.

maybe this is not an issue with the cordova plugin but with the hockeyApp iOS SDK?

**Comment by lostintangent** [comment] 2016-04-07 15:03
@johnyso Running "ionic build ios" is working fine for me :/ Coudl you run "ionic info" and share the output? I just want to try to repro your exact environment.

**Comment by johnyso** [comment] 2016-04-07 15:47
no prob, here is the output: 

```
Cordova CLI: 5.3.3
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic CLI Version: 1.7.12
Ionic App Lib Version: 0.6.5
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v4.2.4
Xcode version: Xcode 7.3 Build version 7D175 
``` 
the ionic CLI is not up to date.

**Comment by lostintangent** [comment] 2016-04-07 16:00
Hmm, OK. I just tried your exact Node, Cordova and Ionic version, and still can't repro the issue. I'm also running El Capitan, but I'm using Xcode 7.2, so it's very possible that introduced a breaking change that we haven't tested yet. I'll upgrade Xcode now and keep investigating. Thanks for all the help!

**Comment by lostintangent** [comment] 2016-04-07 16:05
Could you try one other thing for me? Run the following steps:

1. `cordova plugin rm cordova-plugin-hockeyapp`
2. `cordova plugin add cordova-plugin-hockeyapp@latest`
3. `ionic build ios`

I just want to eliminate the possibility of some odd "plugin corruption" that may have happened when you upgraded. Thanks again!

**Comment by AndrewCer** [comment] 2016-04-07 16:07
Hey @lostintangent. Here's the results of your suggested testing:

1. The error I get when I try to build locally is `CpResource appName/Resources/HockeySDKResources.bundle build/emulator/appName.app/HockeySDKResources.bundle`

2. Never used this plugin before. We just recently found out about HockeyApp and decided to use it to deploy our beta app.

3. `<plugin spec="https://github.com/bitstadium/HockeySDK-Cordova.git" />` &  `<plugin name="cordova-plugin-hockeyapp" />`  both pull from git, install, and then break the same as before.

**Comment by lostintangent** [comment] 2016-04-07 16:10
@AndrewCer What version of Xcode do you have installed?

**Comment by AndrewCer** [comment] 2016-04-07 16:16
Version 7.3 
Build Version 7D175

**Comment by lostintangent** [comment] 2016-04-07 16:17
OK, interesting. You and @johnyso are both hitting this issue and are both running Xcode 7.3, so I'm upgrading my Xcode install to 7.3 and will report back. We'll try to get this working ASAP. Thanks for the patience!

**Comment by AndrewCer** [comment] 2016-04-07 16:39
Thanks for all the help! Keep us posted.

Also, same as johnyso, reverting to version 2.1.0 results in zero build errors on PhoneGap build.
config.xml: `<plugin name="cordova-plugin-hockeyapp" version="2.1.0"/>`

**Comment by lostintangent** [comment] 2016-04-07 18:42
One final question guys! Can you run `cordova platform ls` and let me know which version of Cordova iOS you are running?

**Comment by AndrewCer** [comment] 2016-04-07 19:28
`Installed platforms: ios 4.0.1`
`Available platforms: amazon-fireos, android, blackberry10, browser, firefoxos, osx, webos`

**Comment by lostintangent** [comment] 2016-04-07 21:33
@AndrewCer @johnyso We just submitted a fix for this, and it would be awesome to have you verify it on your end. Could you remove and re-add the plugin from this GitHub repo and let us know if your project builds successfully? If so, we can release it to NPM. Thanks!

**Comment by johnyso** [comment] 2016-04-08 07:03
@lostintangent awesome, thanks so much! 
It's working with the plugin from this GitHub repo. I also checked if the plugin functions where triggered. Everything works fine!

thanks for this quick fix guys!

**Comment by lostintangent** [comment] 2016-04-08 15:15
Perfect, thanks for confirming that. We'll release the update to NPM this morning.

**Comment by AndrewCer** [comment] 2016-04-08 15:35
@lostintangent Everything is working on my end too. PhoneGap and local build. Thanks for being so responsive and awesome!

**Comment by lostintangent** [comment] 2016-04-08 16:09
Yay! OK cool, I'll close this issue then and we'll release `2.2.2` to NPM in just a few minutes. Thanks guys for all your help tracking this down!

**Closed by lostintangent** 2016-04-08 16:09 UTC

**Comment by xavianaxw** [comment] 2016-07-27 17:32
@lostintangent sorry for commenting on an old post. I'm not actually using HockeySDK but I'm facing a similar problem with Andrew regarding a custom built Cordova plugin. I was just wondering what did you modify to make it work?
